version: 0.0.4

branches:
  only:
    - main
    
artifacts:
  - path: C:\projects\postgresql-14.0\src\interfaces\libpq\libpq.dll
    name: libpq

build_script: |
  C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
  C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
  C:\msys64\usr\bin\bash -lc "pacman -S --needed base-devel mingw-w64-x86_64-toolchain"
  set CHERE_INVOKING=yes
  set MSYSTEM=MINGW64
  C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
  call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  set PATH=C:\Qt\5.14.2\msvc2017_64\bin;C:\Qt\Tools\QtCreator\bin\jom;C:\Python39-x64;C:\Python39-x64\Scripts;%PATH%
  cd ..
  curl -L -o postgresql-14.0.tar.bz2 https://ftp.postgresql.org/pub/source/v14.0/postgresql-14.0.tar.bz2
  7z x postgresql-14.0.tar.bz2
  cd postgresql-14.0
  copy /y %APPVEYOR_BUILD_FOLDER%\build.sh .
  C:\msys64\usr\bin\bash -lc "./build"
